ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། མཉམ་མེད་དྭགས་པོ་ལྷ་རྗེ།
  - མཛད་པ་པོ། སློབ་དཔོན་སྒོམ་པ་བ།
  - མཛད་པ་པོ། ཞྭ་དམར་བཞི་པ་ཆོས་ཀྱི་གྲགས་པ།
  - མཛད་པ་པོ། ལྷོ་ལ་ཡག་པ་བྱང་ཆུབ་དངོས་གྲུབ།
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  sku: RDI-SS-03
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: Commentaries on the Four Dharmas of Gampopa
    bo: མཉམ་མེད་དྭགས་པོ་ཆོས་བཞིའི་དགོངས་འགྲེལ།
  collection:
    en: RDI Study Series–  Book 3
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༣
  author:
    en: Fourth Shamar Chokyi Drakpa,Hlolayagpa Jangchub Ngodrup,Je Gampopa,Kunkhyen
      Pema Karpo,Nyame Dagpo Lhaje
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།,མཉམ་མེད་དྭགས་པོ་ལྷ་རྗེ།,ཞྭ་དམར་སྐུ་ཕྲེང་བཞི་པ་ཆོས་ཀྱི་གྲགས་པ།,རྗེ་སྒམ་པོ་པ།,ལྷོ་ལ་ཡག་པ་བྱུང་ཆུབ་དངོས་གྲུབ།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-03
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-03.epub
  description:
    en: ༄༅། །བཀའ་ཕྱག་ཟུང་གི་གདམས་པའི་འོ་རྒྱུན་ཐོས་པའི་རྒྱ་མཚོར་ལེགས་པར་བསྐྱིལ་ཅིང་།
      བསམ་པའི་སྲུབ་སྦྱོར་གྱིས་དཀྲོགས་པའི་མར་ལོས་ཏིང་འཛིན་སྒོམ་པའི་ལྟོ་བ་འགྲངས་པར་སྤྱོད་པས་རྣམ་བྱང་གི་ལང་འཚོ་རྟག་བརྟན་བགྲེས་རྒུད་དང་བྲལ་ཞིང་།
      གཞན་དོན་གྱི་ཁུར་མི་ངལ་བར་ཐེག་པའི་མཐུ་སྟོབས་རྟག་ཁྱབ་ལྷུན་གྲུབ་ཏུ་རྫོགས་པའི་ཆོས་རྒྱལ་ཆེན་པོ་མཉམ་མེད་དྭགས་པོ་ལྷ་རྗེས་གཞན་དོན་གསུང་གི་ཕྲིན་ལས་སྐྱེས་བུ་གསུམ་གྱི་སྐལ་མཉམ་དུ་འགྱེད་པས་རྒྱུད་སྨིན་ཅིང་གྲོལ་བའི་འཁོར་དག་པ་ནི་ནམ་མཁའི་རྒྱུ་སྐར་གྱི་གྲངས་ལས་འདས་པ་བྱུང་ལ།
      གསུང་གི་ཕུང་པོ་དེ་དག་གི་སྙིང་པོ་བཅུད་དུ་ཕྱུང་པ་ནི་དྭགས་པོའི་ཆོས་བཞི་སྟེ་བློ་ཆོས་སུ་འགྲོ་བ།
      ཆོས་ལམ་དུ་འགྲོ་བ། ལམ་འཁྲུལ་བ་སེལ་བ། འཁྲུལ་པ་ཡེ་ཤེས་སུ་འཆར་བ་ཞེས་མདོ་སྔགས་མན་ངག་དང་བཅས་པའི་མདོ་དོན་གསལ་དག་ཟབ་གསུམ་དུ་རྩ་བ་སྒྲོམ་བཞིར་བསྡུས་ཡོད་པ་དང་།
      དེ་ལའང་རྗེས་འཇུག་ཐུགས་སྲས་རྣམས་ཀྱིས་དགོངས་པ་འགྲེལ་ཚུལ་སྣ་ཚོགས་སུ་བཞུགས་པ་སོ་སོར་ཐུན་མིན་ཁྱད་ཆོས་སུ་ལྡན་པར་དམིགས་ནས་དཀྱུས་གཅིག་ཏུ་བཀོད་པའོ།
      །
    bo: ༄༅། །བཀའ་ཕྱག་ཟུང་གི་གདམས་པའི་འོ་རྒྱུན་ཐོས་པའི་རྒྱ་མཚོར་ལེགས་པར་བསྐྱིལ་ཅིང་།
      བསམ་པའི་སྲུབ་སྦྱོར་གྱིས་དཀྲོགས་པའི་མར་ལོས་ཏིང་འཛིན་སྒོམ་པའི་ལྟོ་བ་འགྲངས་པར་སྤྱོད་པས་རྣམ་བྱང་གི་ལང་འཚོ་རྟག་བརྟན་བགྲེས་རྒུད་དང་བྲལ་ཞིང་།
      གཞན་དོན་གྱི་ཁུར་མི་ངལ་བར་ཐེག་པའི་མཐུ་སྟོབས་རྟག་ཁྱབ་ལྷུན་གྲུབ་ཏུ་རྫོགས་པའི་ཆོས་རྒྱལ་ཆེན་པོ་མཉམ་མེད་དྭགས་པོ་ལྷ་རྗེས་གཞན་དོན་གསུང་གི་ཕྲིན་ལས་སྐྱེས་བུ་གསུམ་གྱི་སྐལ་མཉམ་དུ་འགྱེད་པས་རྒྱུད་སྨིན་ཅིང་གྲོལ་བའི་འཁོར་དག་པ་ནི་ནམ་མཁའི་རྒྱུ་སྐར་གྱི་གྲངས་ལས་འདས་པ་བྱུང་ལ།
      གསུང་གི་ཕུང་པོ་དེ་དག་གི་སྙིང་པོ་བཅུད་དུ་ཕྱུང་པ་ནི་དྭགས་པོའི་ཆོས་བཞི་སྟེ་བློ་ཆོས་སུ་འགྲོ་བ།
      ཆོས་ལམ་དུ་འགྲོ་བ། ལམ་འཁྲུལ་བ་སེལ་བ། འཁྲུལ་པ་ཡེ་ཤེས་སུ་འཆར་བ་ཞེས་མདོ་སྔགས་མན་ངག་དང་བཅས་པའི་མདོ་དོན་གསལ་དག་ཟབ་གསུམ་དུ་རྩ་བ་སྒྲོམ་བཞིར་བསྡུས་ཡོད་པ་དང་།
      དེ་ལའང་རྗེས་འཇུག་ཐུགས་སྲས་རྣམས་ཀྱིས་དགོངས་པ་འགྲེལ་ཚུལ་སྣ་ཚོགས་སུ་བཞུགས་པ་སོ་སོར་ཐུན་མིན་ཁྱད་ཆོས་སུ་ལྡན་པར་དམིགས་ནས་དཀྱུས་གཅིག་ཏུ་བཀོད་པའོ།
      །
